const foodList = [
  'gyros',
  'greek',
  'moussaka',
  'souvlaki',
  'spanakopita',
  'gazpacho',
  'baked ziti',
  'goulash',
  'coq au vin',
  'beef bourguignon',
  'pasta carbonara',
  'spaghetti carbonara',
  'paella',
  'spanish',
  'empanada',
  'pizza',
  'gnocchi',
  'ravioli',
  'calzone',
  'risotto',
  'stew',
  'jjigae',
  'quiche',
  'french',
  'crab',
  'clams',
  'shrimp',
  'oysters',
  'lobster',
  'pho',
  'thai',
  'asian',
  'sushi',
  'salad',
  'salmon',
  'mackerel',
  'steak',
  'burger',
  'gumbo',
  'cajun',
  'cod',
  'hake',
  'pike',
  'carp',
  'tuna',
  'fish',
  'sole',
  'turnover',
  'onion tart',
  'chocolate souffle',
  'vanilla ricotta souffle',
  'souffle',
  'ratatouille',
  'ceviche',
  'po boy',
  'beef stroganoff',
  'spaghetti and meatballs',
  'brisket',
  'meatloaf',
  'southern',
  'cioppino',
  'turkey burgers',
  'french onion soup',
  'hand pies',
  'pastry pillows',
  'souffle dessert',
  'chicken parmesan',
  'german',
  'rouladen',
  'schnitzel',
  'bobotie',
  'african',
  'bunny chow',
  'jollof rice',
  'piri piri chicken',
  'caesar salad',
  'soy burger',
  'crabcakes',
  'grilled cheese sandwich',
  'rib tips',
  'prime rib',
  'beef ribs',
  'cholent',
  'lasagne',
  'italian',
  'curry',
  'chole'
];

export default foodList;
